# Generated by Django 4.2.30 on 2026-07-21 18:53

import config.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_session_hijri_year_term_hijri_end_term_hijri_start'),
        ('users', '0005_user_date_of_birth'),
        ('curriculum', '0002_enrollment_idx_enr_m_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('due_date', models.DateTimeField()),
                ('total_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('file', models.FileField(blank=True, null=True, upload_to='homework/', validators=[config.validators.validate_document])),
                ('is_published', models.BooleanField(default=False)),
                ('late_submission_allowed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('learning_objectives', models.JSONField(blank=True, default=list, help_text='List of learning objectives')),
                ('success_criteria', models.JSONField(blank=True, default=list, help_text='How students know they succeeded')),
                ('keywords', models.JSONField(blank=True, default=list, help_text='Key vocabulary')),
                ('prior_knowledge', models.TextField(blank=True, help_text='What students should already know')),
                ('teaching_materials', models.JSONField(blank=True, default=list, help_text='Materials needed')),
                ('references', models.JSONField(blank=True, default=list, help_text='Textbook references, pages, etc.')),
                ('teaching_methods', models.JSONField(blank=True, default=list, help_text='Teaching methods used')),
                ('duration_minutes', models.PositiveSmallIntegerField(default=45)),
                ('lesson_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('room', models.CharField(blank=True, max_length=100)),
                ('introduction', models.TextField(blank=True, help_text='Opening / hook / review')),
                ('lesson_development', models.TextField(blank=True, help_text='Main teaching content')),
                ('student_activities', models.JSONField(blank=True, default=list, help_text='Student activity descriptions')),
                ('differentiation', models.TextField(blank=True, help_text='How to differentiate for varying abilities')),
                ('assessment', models.TextField(blank=True, help_text='Formative assessment strategy')),
                ('homework', models.TextField(blank=True, help_text='Homework assigned from this lesson')),
                ('resources', models.TextField(blank=True, help_text='Additional resources')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('archived', 'Archived'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('approval_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('ai_generated', models.BooleanField(default=False, help_text='Was any content AI-generated?')),
                ('ai_prompt', models.TextField(blank=True, help_text='The prompt used for AI generation')),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_lessons', to=settings.AUTH_USER_MODEL)),
                ('class_arm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_plans', to='academic.classarm')),
                ('madrasah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='users.madrasah')),
            ],
            options={
                'ordering': ['-lesson_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='SchemeOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. "Quran Memorisation – Term 1"', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schemes', to=settings.AUTH_USER_MODEL)),
                ('madrasah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes_of_work', to='users.madrasah')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes_of_work', to='curriculum.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes_of_work', to='curriculum.subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'ustaadh'}, on_delete=django.db.models.deletion.CASCADE, related_name='schemes_of_work', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes_of_work', to='academic.term')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('madrasah', 'term', 'subject', 'school_class')},
            },
        ),
        migrations.CreateModel(
            name='SchemeWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveSmallIntegerField()),
                ('topic', models.CharField(max_length=255)),
                ('subtopic', models.CharField(blank=True, max_length=255)),
                ('learning_outcomes', models.TextField(blank=True)),
                ('reference_materials', models.TextField(blank=True)),
                ('lesson_count', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='not_started', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='lessons.schemeofwork')),
            ],
            options={
                'ordering': ['week_number'],
                'unique_together': {('scheme', 'week_number')},
            },
        ),
        migrations.CreateModel(
            name='LessonResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('pdf', 'PDF'), ('doc', 'Word Document'), ('ppt', 'PowerPoint'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('link', 'External Link'), ('youtube', 'YouTube'), ('gdrive', 'Google Drive')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, help_text='For external links, YouTube, GDrive')),
                ('file', models.FileField(blank=True, upload_to='lesson_resources/', validators=[config.validators.validate_document])),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources_list', to='lessons.lessonplan')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LessonReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_went_well', models.TextField(blank=True)),
                ('what_to_improve', models.TextField(blank=True)),
                ('student_understanding', models.TextField(blank=True)),
                ('next_steps', models.TextField(blank=True)),
                ('self_rating', models.PositiveSmallIntegerField(default=3, help_text='Teacher self-rating 1-5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to='lessons.lessonplan')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_reflections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='scheme_week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_plans', to='lessons.schemeweek'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='curriculum.schoolclass'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='curriculum.subject'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'ustaadh'}, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_plans', to='academic.term'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='timetable_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_plans', to='academic.timetableslot'),
        ),
        migrations.CreateModel(
            name='LessonDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('delivery_status', models.CharField(choices=[('not_delivered', 'Not Delivered'), ('partially_completed', 'Partially Completed'), ('completed', 'Completed')], default='not_delivered', max_length=20)),
                ('students_present', models.PositiveIntegerField(default=0)),
                ('students_absent', models.PositiveIntegerField(default=0)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('homework_given', models.BooleanField(default=False)),
                ('assessment_conducted', models.BooleanField(default=False)),
                ('actual_duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('challenges', models.TextField(blank=True, help_text='Challenges encountered during delivery')),
                ('recommendations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_deliveries', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='lessons.lessonplan')),
            ],
            options={
                'verbose_name_plural': 'Lesson deliveries',
            },
        ),
        migrations.CreateModel(
            name='LessonAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('model_name', models.CharField(choices=[('lessonplan', 'Lesson Plan'), ('schemeofwork', 'Scheme of Work'), ('lessondelivery', 'Lesson Delivery'), ('lessonreflection', 'Lesson Reflection'), ('lessonresource', 'Lesson Resource')], max_length=50)),
                ('object_id', models.CharField(max_length=100)),
                ('previous_data', models.JSONField(blank=True, default=dict)),
                ('new_data', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonAnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_planned', models.PositiveIntegerField(default=0)),
                ('total_delivered', models.PositiveIntegerField(default=0)),
                ('total_missed', models.PositiveIntegerField(default=0)),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('avg_delivery_duration', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('avg_self_rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_analytics', to='curriculum.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_analytics', to='curriculum.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_analytics', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_analytics', to='academic.term')),
            ],
        ),
        migrations.CreateModel(
            name='LearningObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_objectives', to='curriculum.subject')),
            ],
            options={
                'ordering': ['objective'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='submissions/', validators=[config.validators.validate_generic_file])),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('is_late', models.BooleanField(default=False)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('graded', 'Graded'), ('returned', 'Returned')], default='submitted', max_length=20)),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='lessons.homework')),
                ('madrasah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to='users.madrasah')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='homework',
            name='lesson_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeworks', to='lessons.lessonplan'),
        ),
        migrations.AddField(
            model_name='homework',
            name='madrasah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='users.madrasah'),
        ),
        migrations.AddField(
            model_name='homework',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='curriculum.schoolclass'),
        ),
        migrations.AddField(
            model_name='homework',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='curriculum.subject'),
        ),
        migrations.AddField(
            model_name='homework',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='lessonplan',
            index=models.Index(fields=['madrasah', 'teacher', 'status'], name='idx_lp_m_teacher'),
        ),
        migrations.AddIndex(
            model_name='lessonplan',
            index=models.Index(fields=['madrasah', 'subject', 'school_class'], name='idx_lp_m_sub_cls'),
        ),
        migrations.AddIndex(
            model_name='lessonplan',
            index=models.Index(fields=['lesson_date'], name='idx_lp_date'),
        ),
        migrations.AddIndex(
            model_name='lessonplan',
            index=models.Index(fields=['status'], name='idx_lp_status'),
        ),
        migrations.AddIndex(
            model_name='lessonauditlog',
            index=models.Index(fields=['model_name', 'object_id'], name='idx_laudit_model'),
        ),
        migrations.AddIndex(
            model_name='lessonauditlog',
            index=models.Index(fields=['actor'], name='idx_laudit_actor'),
        ),
        migrations.AlterUniqueTogether(
            name='lessonanalyticssnapshot',
            unique_together={('teacher', 'subject', 'school_class', 'term')},
        ),
        migrations.AddIndex(
            model_name='homeworksubmission',
            index=models.Index(fields=['madrasah', 'status'], name='idx_sub_m_status'),
        ),
        migrations.AlterUniqueTogether(
            name='homeworksubmission',
            unique_together={('homework', 'student')},
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['madrasah', 'teacher'], name='idx_hw_m_teacher'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['madrasah', 'is_published'], name='idx_hw_m_published'),
        ),
    ]
