# Generated by Django 4.2.30 on 2026-07-20 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('users', '0002_message'),
        ('curriculum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('lesson_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('objectives', models.TextField()),
                ('resources', models.TextField(blank=True)),
                ('homework', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('approval_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'mudeer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_lesson_plans', to=settings.AUTH_USER_MODEL)),
                ('class_arm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_plans', to='academic.classarm')),
                ('madrasah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='users.madrasah')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='curriculum.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='curriculum.subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'ustaadh'}, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_plans', to='academic.term')),
            ],
            options={
                'ordering': ['-lesson_date', 'start_time'],
                'unique_together': {('madrasah', 'teacher', 'lesson_date', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('due_date', models.DateTimeField()),
                ('total_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=False)),
                ('late_submission_allowed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeworks', to='lessons.lessonplan')),
                ('madrasah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='users.madrasah')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='curriculum.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='curriculum.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(blank=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('is_late', models.BooleanField(default=False)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('graded', 'Graded'), ('returned', 'Returned')], default='submitted', max_length=20)),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='lessons.homework')),
                ('madrasah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to='users.madrasah')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('homework', 'student')},
            },
        ),
    ]
