# Generated by Django 4.2.30 on 2026-07-20 18:53

import config.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_homework_file_homeworksubmission_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='homework/', validators=[config.validators.validate_document]),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/', validators=[config.validators.validate_generic_file]),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['madrasah', 'teacher'], name='idx_hw_m_teacher'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['madrasah', 'is_published'], name='idx_hw_m_published'),
        ),
        migrations.AddIndex(
            model_name='homeworksubmission',
            index=models.Index(fields=['madrasah', 'status'], name='idx_sub_m_status'),
        ),
    ]
