# Generated by Django 4.2.30 on 2026-07-23 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_user_date_of_birth'),
        ('curriculum', '0002_enrollment_idx_enr_m_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic', '0002_session_hijri_year_term_hijri_end_term_hijri_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('true_false', 'True / False')], default='mcq', max_length=20)),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard'), (4, 'Expert'), (5, 'Master')], default=2)),
                ('marks', models.DecimalField(decimal_places=2, default=1.0, max_digits=6)),
                ('question_text', models.TextField(help_text='Question text (supports Arabic RTL)')),
                ('question_text_ar', models.TextField(blank=True, default='', help_text='Arabic question text')),
                ('options', models.JSONField(blank=True, default=list, help_text='MCQ: [{"key":"A","text":"...","text_ar":"..."},...]  T/F: auto-generated')),
                ('correct_answer', models.CharField(help_text='Option key: A, B, C, D or true/false', max_length=10)),
                ('explanation', models.TextField(blank=True, default='', help_text='Explanation shown after submission')),
                ('explanation_ar', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_new_quiz_questions', to=settings.AUTH_USER_MODEL)),
                ('madrasah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_assessments', to='users.madrasah')),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_assessments', to='curriculum.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_assessments', to='curriculum.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_assessments', to='curriculum.topic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('instructions', models.TextField(blank=True, default='')),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard'), (4, 'Expert'), (5, 'Master')], default=2)),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=30)),
                ('available_from', models.DateTimeField(blank=True, null=True)),
                ('available_until', models.DateTimeField(blank=True, null=True)),
                ('time_limit_minutes', models.PositiveIntegerField(default=30)),
                ('grace_period_minutes', models.PositiveIntegerField(default=5, help_text='Extra time after expiry for submission')),
                ('max_attempts', models.PositiveIntegerField(default=1)),
                ('passing_score', models.DecimalField(decimal_places=2, default=60.0, max_digits=5)),
                ('marks_per_question', models.DecimalField(decimal_places=2, default=1.0, max_digits=6)),
                ('negative_marking', models.BooleanField(default=False)),
                ('negative_mark_fraction', models.DecimalField(decimal_places=2, default=0.25, help_text='Fraction of marks deducted for wrong answer', max_digits=3)),
                ('randomize_questions', models.BooleanField(default=False)),
                ('randomize_options', models.BooleanField(default=False)),
                ('one_question_per_page', models.BooleanField(default=True)),
                ('allow_review', models.BooleanField(default=True)),
                ('allow_back_navigation', models.BooleanField(default=True)),
                ('show_question_numbers', models.BooleanField(default=True)),
                ('auto_save', models.BooleanField(default=True)),
                ('grading_mode', models.CharField(choices=[('auto_immediate', 'Auto Grade + Release Immediately'), ('auto_release_later', 'Auto Grade + Teacher Releases Later'), ('manual', 'Teacher Grades + Releases')], default='auto_release_later', max_length=30)),
                ('require_fullscreen', models.BooleanField(default=False)),
                ('max_violations', models.PositiveIntegerField(default=5)),
                ('auto_submit_on_violations', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_new_quizzes', to=settings.AUTH_USER_MODEL)),
                ('madrasah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_quizzes', to='users.madrasah')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_quizzes', to='curriculum.schoolclass')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_quizzes', to='academic.session')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_quizzes', to='curriculum.subject')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_quizzes', to='academic.term')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('graded', 'Graded'), ('released', 'Released')], default='in_progress', max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('total_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_pass', models.BooleanField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('madrasah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='users.madrasah')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quizzes.quiz')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='new_quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_to_all', models.BooleanField(default=True, help_text='Assign to all students in class')),
                ('student_ids', models.JSONField(blank=True, default=list, help_text='Specific student IDs if not all')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='quizzes.quiz')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_assignments', to='curriculum.schoolclass')),
            ],
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(blank=True, default='', max_length=10)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('marks_awarded', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_flagged', models.BooleanField(default=False)),
                ('time_spent_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.quizattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answers', to='quizzes.question')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ViolationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('tab_switch', 'Tab Switch'), ('window_blur', 'Window Blur'), ('copy_attempt', 'Copy Attempt'), ('paste_attempt', 'Paste Attempt'), ('fullscreen_exit', 'Fullscreen Exit'), ('right_click', 'Right Click'), ('keyboard_shortcut', 'Keyboard Shortcut')], max_length=30)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='quizzes.quizattempt')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['attempt', 'violation_type'], name='idx_vl_attempt_type')],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('marks', models.DecimalField(blank=True, decimal_places=2, help_text='Override marks for this quiz (null = use question default)', max_digits=6, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_links', to='quizzes.question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='quizzes.quiz')),
            ],
            options={
                'ordering': ['sort_order'],
                'unique_together': {('quiz', 'question')},
            },
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['student', 'quiz'], name='idx_qza_student_quiz'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['quiz', 'status'], name='idx_qza_quiz_status'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['madrasah', 'status'], name='idx_qza_m_status'),
        ),
        migrations.AlterUniqueTogether(
            name='quizattempt',
            unique_together={('quiz', 'student', 'attempt_number')},
        ),
        migrations.AlterUniqueTogether(
            name='quizassignment',
            unique_together={('quiz', 'school_class')},
        ),
        migrations.AlterUniqueTogether(
            name='quizanswer',
            unique_together={('attempt', 'question')},
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['madrasah', 'status'], name='idx_qz_m_status'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['madrasah', 'subject'], name='idx_qz_m_subject'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['madrasah', 'school_class'], name='idx_qz_m_class'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['is_published'], name='idx_qz_published'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['madrasah', 'subject'], name='idx_qzq_m_subject'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['madrasah', 'question_type'], name='idx_qzq_m_type'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_active'], name='idx_qzq_active'),
        ),
    ]
