# Generated by Django 4.2.30 on 2026-08-01 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_banks', '0001_initial'),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_questions', to='question_banks.questionbank'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='source_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_quizzes', to='question_banks.questionbank'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('true_false', 'True / False'), ('short_answer', 'Short Answer')], default='mcq', max_length=20),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='selected_answer',
            field=models.TextField(blank=True, default=''),
        ),
    ]
