# Generated by Django 4.2.30 on 2026-08-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_question_question_bank_quiz_source_bank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('true_false', 'True / False'), ('short_answer', 'Short Answer'), ('essay', 'Essay')], default='mcq', max_length=20),
        ),
    ]
