# Generated by Django 4.2.30 on 2026-08-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_alter_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(help_text='Option key: A, B, C, D or true/false, or the answer text for short answer/essay', max_length=255),
        ),
    ]
