# Generated by Django 4.2.30 on 2026-08-01 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curriculum', '0002_enrollment_idx_enr_m_student'),
        ('academic', '0002_session_hijri_year_term_hijri_end_term_hijri_start'),
        ('users', '0007_alter_user_role'),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('file', models.FileField(upload_to='question_banks/%Y/%m/')),
                ('file_type', models.CharField(choices=[('docx', 'Word Document'), ('pdf', 'PDF')], max_length=10)),
                ('original_size', models.PositiveBigIntegerField(default=0, help_text='Size of the original uploaded file in bytes')),
                ('stored_size', models.PositiveBigIntegerField(default=0, help_text='Size of the archived file in bytes')),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_banks', to='quizzes.quiz')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_question_banks', to=settings.AUTH_USER_MODEL)),
                ('madrasah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_banks', to='users.madrasah')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_banks', to='curriculum.schoolclass')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_banks', to='academic.session')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_banks', to='curriculum.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_banks', to='academic.term')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GapAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gap_analyses', to='quizzes.quizattempt')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gap_analyses', to='question_banks.questionbank')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gap_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='questionbank',
            constraint=models.UniqueConstraint(fields=('madrasah', 'subject', 'school_class', 'term'), name='unique_bank_per_term'),
        ),
        migrations.AlterUniqueTogether(
            name='gapanalysis',
            unique_together={('bank', 'student', 'attempt')},
        ),
    ]
