# Generated by Django 4.2.30 on 2026-07-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['student', 'submitted_at'], name='idx_qa_student_submitted'),
        ),
    ]
