# Generated by Django 4.2.30 on 2026-07-20 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        ('users', '0002_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('application_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('address', models.TextField()),
                ('previous_school', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('interview_scheduled', 'Interview Scheduled'), ('interviewed', 'Interviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('enrolled', 'Enrolled')], default='pending', max_length=20)),
                ('interview_date', models.DateTimeField(blank=True, null=True)),
                ('interview_notes', models.TextField(blank=True)),
                ('entrance_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('entrance_result', models.JSONField(blank=True, default=dict)),
                ('accepted_at', models.DateTimeField(null=True)),
                ('enrolled_at', models.DateTimeField(null=True)),
                ('rejected_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applying_for_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='curriculum.schoolclass')),
                ('madrasah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='users.madrasah')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('birth_certificate', 'Birth Certificate'), ('passport_photo', 'Passport Photo'), ('previous_report', 'Previous Report'), ('transfer_letter', 'Transfer Letter'), ('medical_record', 'Medical Record'), ('other', 'Other')], max_length=50)),
                ('file', models.FileField(upload_to='applications/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admissions.application')),
            ],
        ),
    ]
