# Generated by Django 4.2.30 on 2026-07-20 18:53

import config.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdocument',
            name='file',
            field=models.FileField(upload_to='applications/documents/', validators=[config.validators.validate_document]),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['madrasah', 'status'], name='idx_app_m_status'),
        ),
    ]
