# Generated by Django 4.2.30 on 2026-07-20 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('project', 'Project'), ('certificate', 'Certificate'), ('award', 'Award'), ('achievement', 'Achievement'), ('video', 'Video'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='portfolios/')),
                ('date_achieved', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('madrasah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_portfolios', to='users.madrasah')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_achieved', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(choices=[('problem_solving', 'Problem Solving'), ('creativity', 'Creativity'), ('communication', 'Communication'), ('leadership', 'Leadership'), ('critical_thinking', 'Critical Thinking')], max_length=100)),
                ('score', models.IntegerField()),
                ('assessment_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('madrasah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_assessments', to='users.madrasah')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_assessments', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_assessments_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assessment_date'],
                'unique_together': {('student', 'skill_name', 'assessment_date')},
            },
        ),
        migrations.CreateModel(
            name='AtRiskPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('factors', models.JSONField(default=dict)),
                ('recommendations', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('madrasah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='at_risk_predictions', to='users.madrasah')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='at_risk_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-risk_score'],
                'unique_together': {('madrasah', 'student')},
            },
        ),
    ]
