# Generated by Django 4.2.30 on 2026-07-20 18:53

import config.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalportfolio',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='portfolios/', validators=[config.validators.validate_generic_file]),
        ),
    ]
