# Generated by Django 4.2.30 on 2026-07-20 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_message'),
        ('curriculum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.TextField()),
                ('back', models.TextField()),
                ('hint', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('current_level', models.IntegerField(default=1)),
                ('total_levels', models.IntegerField(default=10)),
                ('progress_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('madrasah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths', to='users.madrasah')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths', to='curriculum.subject')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='FlashCardReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.IntegerField()),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('next_review', models.DateTimeField()),
                ('interval_days', models.IntegerField(default=1)),
                ('easiness_factor', models.DecimalField(decimal_places=2, default=2.5, max_digits=4)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='learning.flashcard')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='FlashCardDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_shared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_flashcard_decks', to=settings.AUTH_USER_MODEL)),
                ('madrasah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_decks', to='users.madrasah')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flashcard_decks', to='curriculum.subject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='flashcard',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='learning.flashcarddeck'),
        ),
        migrations.CreateModel(
            name='LearningPathItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('item_type', models.CharField(choices=[('lesson', 'Lesson'), ('quiz', 'Quiz'), ('practice', 'Practice'), ('video', 'Video'), ('reading', 'Reading'), ('project', 'Project')], max_length=20)),
                ('content', models.TextField(blank=True)),
                ('order', models.IntegerField()),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='learning.learningpath')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('learning_path', 'order')},
            },
        ),
    ]
