# Generated by Django 4.2.30 on 2026-07-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='learningpath',
            index=models.Index(fields=['student', 'is_active'], name='idx_lp_student_active'),
        ),
    ]
