# Generated by Django 4.2.30 on 2026-07-22 07:41

import config.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_user_date_of_birth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curriculum', '0002_enrollment_idx_enr_m_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_ar', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Emoji or icon identifier', max_length=50)),
                ('category', models.CharField(choices=[('milestone', 'Milestone'), ('streak', 'Streak'), ('level', 'Level'), ('special', 'Special')], max_length=20)),
                ('criteria', models.JSONField(default=dict, help_text='Award criteria, e.g. {"type": "streak", "value": 7}')),
                ('points', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('madrasah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fasaaha_badges', to='users.madrasah')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='English title', max_length=200)),
                ('title_ar', models.CharField(help_text='Arabic title', max_length=200)),
                ('prompt_ar', models.TextField(help_text='Arabic prompt text')),
                ('prompt_transliteration', models.TextField(blank=True, help_text='Latin script transliteration')),
                ('prompt_translation', models.TextField(help_text='English translation of the prompt')),
                ('expected_phrases', models.JSONField(blank=True, default=list, help_text='Expected vocabulary/phrases')),
                ('hints', models.JSONField(blank=True, default=list)),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard'), (4, 'Expert'), (5, 'Master')], default=2)),
                ('max_time_seconds', models.PositiveIntegerField(default=60, help_text='Max recording time in seconds')),
                ('example_audio', models.FileField(blank=True, null=True, upload_to='fasaaha/examples/', validators=[config.validators.validate_audio])),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['level__number', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SpeakingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('audio_file', models.FileField(upload_to='fasaaha/recordings/%Y/%m/', validators=[config.validators.validate_audio])),
                ('audio_duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('audio_size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional student notes')),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('reviewed', 'Reviewed')], default='processing', max_length=20)),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('is_best_attempt', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('madrasah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fasaaha_attempts', to='users.madrasah')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='fasaaha.mission')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='fasaaha_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpeakingLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(help_text='Level number (1-10)')),
                ('name', models.CharField(help_text='English name', max_length=100)),
                ('name_ar', models.CharField(help_text='Arabic name', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('target_vocabulary_count', models.PositiveIntegerField(default=50)),
                ('difficulty', models.PositiveSmallIntegerField(default=1, help_text='Overall difficulty 1-5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('madrasah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fasaaha_levels', to='users.madrasah')),
            ],
            options={
                'ordering': ['sort_order', 'number'],
                'unique_together': {('madrasah', 'number')},
            },
        ),
        migrations.CreateModel(
            name='MissionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='English name', max_length=100)),
                ('name_ar', models.CharField(help_text='Arabic name', max_length=100)),
                ('icon', models.CharField(blank=True, help_text='Emoji or icon class', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('madrasah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fasaaha_categories', to='users.madrasah')),
            ],
            options={
                'verbose_name_plural': 'Mission categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MissionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fasaaha_assignments_created', to=settings.AUTH_USER_MODEL)),
                ('madrasah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fasaaha_assignments', to='users.madrasah')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='fasaaha.mission')),
                ('target_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fasaaha_assignments', to='curriculum.schoolclass')),
                ('target_student', models.ForeignKey(blank=True, limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fasaaha_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='mission',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='fasaaha.missioncategory'),
        ),
        migrations.AddField(
            model_name='mission',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fasaaha_missions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mission',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='fasaaha.speakinglevel'),
        ),
        migrations.AddField(
            model_name='mission',
            name='madrasah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fasaaha_missions', to='users.madrasah'),
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcribed_text', models.TextField(blank=True, help_text='STT output')),
                ('transcription_provider', models.CharField(blank=True, choices=[('whisper', 'Whisper'), ('azure_speech', 'Azure Speech'), ('google_speech', 'Google Speech'), ('local_whisper', 'Local Whisper')], max_length=30)),
                ('transcription_confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('transcription_raw', models.JSONField(blank=True, default=dict, help_text='Full provider response')),
                ('pronunciation_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grammar_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fluency_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('vocabulary_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pronunciation_feedback', models.JSONField(blank=True, default=dict)),
                ('grammar_feedback', models.JSONField(blank=True, default=dict)),
                ('fluency_feedback', models.JSONField(blank=True, default=dict)),
                ('word_scores', models.JSONField(blank=True, default=list, help_text='[{word, score, issues}]')),
                ('scoring_provider', models.CharField(blank=True, max_length=30)),
                ('processing_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, default=dict, help_text='Full AI response')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='fasaaha.speakingattempt')),
                ('madrasah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fasaaha_analyses', to='users.madrasah')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, help_text='Override score (null = use AI score)', max_digits=5, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('pronunciation_notes', models.TextField(blank=True)),
                ('grammar_notes', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(blank=True, help_text='null=pending, true=approved, false=needs_work', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_reviews', to='fasaaha.speakingattempt')),
                ('madrasah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fasaaha_reviews', to='users.madrasah')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'ustaadh'}, on_delete=django.db.models.deletion.CASCADE, related_name='fasaaha_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('attempt', 'teacher')},
            },
        ),
        migrations.CreateModel(
            name='StudentStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_practice_date', models.DateField(blank=True, null=True)),
                ('total_practice_days', models.PositiveIntegerField(default=0)),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('madrasah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fasaaha_streaks', to='users.madrasah')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='fasaaha_streaks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'madrasah')},
            },
        ),
        migrations.CreateModel(
            name='StudentLevelProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('mastered', 'Mastered')], default='not_started', max_length=20)),
                ('missions_attempted', models.PositiveIntegerField(default=0)),
                ('missions_completed', models.PositiveIntegerField(default=0, help_text='Missions with score >= 70')),
                ('average_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('best_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_time_seconds', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='fasaaha.speakinglevel')),
                ('madrasah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fasaaha_level_progress', to='users.madrasah')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='fasaaha_level_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['level__number'],
                'unique_together': {('student', 'level')},
            },
        ),
        migrations.CreateModel(
            name='StudentBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('awarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fasaaha_badges_awarded', to=settings.AUTH_USER_MODEL)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_to', to='fasaaha.badge')),
                ('madrasah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fasaaha_student_badges', to='users.madrasah')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='fasaaha_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-awarded_at'],
                'unique_together': {('student', 'badge')},
            },
        ),
        migrations.AddIndex(
            model_name='speakingattempt',
            index=models.Index(fields=['madrasah', 'student', 'mission'], name='idx_sa_m_s_m'),
        ),
        migrations.AddIndex(
            model_name='speakingattempt',
            index=models.Index(fields=['madrasah', 'status'], name='idx_sa_m_status'),
        ),
        migrations.AddIndex(
            model_name='speakingattempt',
            index=models.Index(fields=['student', 'mission', 'is_best_attempt'], name='idx_sa_best'),
        ),
        migrations.AlterUniqueTogether(
            name='speakingattempt',
            unique_together={('student', 'mission', 'attempt_number')},
        ),
        migrations.AlterUniqueTogether(
            name='missioncategory',
            unique_together={('madrasah', 'name')},
        ),
        migrations.AddIndex(
            model_name='missionassignment',
            index=models.Index(fields=['madrasah', 'mission'], name='idx_fma_m_m'),
        ),
        migrations.AddIndex(
            model_name='missionassignment',
            index=models.Index(fields=['target_student'], name='idx_fma_student'),
        ),
        migrations.AddIndex(
            model_name='missionassignment',
            index=models.Index(fields=['target_class'], name='idx_fma_class'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['madrasah', 'level'], name='idx_fm_m_level'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['madrasah', 'category'], name='idx_fm_m_cat'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['is_active'], name='idx_fm_active'),
        ),
        migrations.AlterUniqueTogether(
            name='mission',
            unique_together={('madrasah', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='badge',
            unique_together={('madrasah', 'name')},
        ),
        migrations.AddIndex(
            model_name='aianalysis',
            index=models.Index(fields=['attempt', 'created_at'], name='idx_aa_attempt'),
        ),
    ]
