# Generated by Django 4.2.30 on 2026-07-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fasaaha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='confidence_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Voice confidence (0-100)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='fluency_pause_ratio',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Ratio of pause time to total time', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='fluency_words_per_minute',
            field=models.PositiveIntegerField(blank=True, help_text='Speech rate in words per minute', null=True),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='topic_relevance_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Topic relevance (0-100)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='mission_type',
            field=models.CharField(choices=[('reading', 'Reading'), ('pronunciation', 'Pronunciation'), ('repeat_after_me', 'Repeat After Me'), ('free_speaking', 'Free Speaking'), ('storytelling', 'Storytelling'), ('picture_description', 'Picture Description'), ('conversation', 'Conversation'), ('role_play', 'Role Play'), ('debate', 'Debate'), ('presentation', 'Presentation')], default='pronunciation', help_text='Type of speaking activity', max_length=30),
        ),
        migrations.AddField(
            model_name='speakingattempt',
            name='activity_type',
            field=models.CharField(choices=[('reading', 'Reading'), ('pronunciation', 'Pronunciation'), ('repeat_after_me', 'Repeat After Me'), ('free_speaking', 'Free Speaking'), ('storytelling', 'Storytelling'), ('picture_description', 'Picture Description'), ('conversation', 'Conversation'), ('role_play', 'Role Play'), ('debate', 'Debate'), ('presentation', 'Presentation')], default='pronunciation', help_text='Activity type at time of submission', max_length=30),
        ),
    ]
