# Generated by Django 4.2.30 on 2026-07-23 13:06

import config.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_user_date_of_birth'),
        ('fasaaha', '0002_add_mission_type_activity_type_and_ai_confidence_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DialogueSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('topic', models.CharField(choices=[('daily_life', 'Daily Life'), ('greetings', 'Greetings'), ('shopping', 'Shopping'), ('family', 'Family'), ('school', 'School'), ('food', 'Food & Dining'), ('travel', 'Travel'), ('health', 'Health'), ('free', 'Free Conversation')], default='free', max_length=30)),
                ('level_number', models.PositiveSmallIntegerField(default=1, help_text='Difficulty level for AI responses')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('turn_count', models.PositiveIntegerField(default=0)),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('madrasah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fasaaha_dialogues', to='users.madrasah')),
                ('mission', models.ForeignKey(blank=True, help_text='Linked mission if conversation-based', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dialogue_sessions', to='fasaaha.mission')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='fasaaha_dialogues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('missions_target', models.PositiveIntegerField(default=3, help_text='Number of missions to complete')),
                ('missions_completed', models.PositiveIntegerField(default=0)),
                ('minutes_target', models.PositiveIntegerField(default=15, help_text='Minutes of practice')),
                ('minutes_practiced', models.PositiveIntegerField(default=0)),
                ('streak_target', models.PositiveIntegerField(default=1, help_text='Days of streak to maintain')),
                ('is_achieved', models.BooleanField(default=False)),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('madrasah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fasaaha_goals', to='users.madrasah')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='fasaaha_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('all_time', 'All Time')], max_length=10)),
                ('period_start', models.DateField()),
                ('points', models.PositiveIntegerField(default=0)),
                ('missions_completed', models.PositiveIntegerField(default=0)),
                ('average_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('madrasah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fasaaha_leaderboard', to='users.madrasah')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='fasaaha_leaderboard', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-points', '-average_score'],
                'indexes': [models.Index(fields=['madrasah', 'period', 'period_start'], name='idx_lb_m_p_ps')],
                'unique_together': {('student', 'madrasah', 'period', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='DialogueTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('ai', 'AI')], max_length=10)),
                ('text_ar', models.TextField(help_text='Arabic text')),
                ('text_en', models.TextField(blank=True, help_text='English translation')),
                ('transliteration', models.TextField(blank=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='fasaaha/dialogues/%Y/%m/', validators=[config.validators.validate_audio])),
                ('pronunciation_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fluency_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('vocabulary_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('turn_score', models.DecimalField(blank=True, decimal_places=2, help_text='Composite score for this turn', max_digits=5, null=True)),
                ('ai_context', models.JSONField(blank=True, default=dict, help_text='AI response metadata, suggestions, corrections')),
                ('correction', models.TextField(blank=True, help_text='AI correction of student response if applicable')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='fasaaha.dialoguesession')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
                'indexes': [models.Index(fields=['session', 'role'], name='idx_dt_s_r')],
            },
        ),
        migrations.AddIndex(
            model_name='dialoguesession',
            index=models.Index(fields=['madrasah', 'student'], name='idx_ds_m_s'),
        ),
        migrations.AddIndex(
            model_name='dialoguesession',
            index=models.Index(fields=['status'], name='idx_ds_status'),
        ),
        migrations.AlterUniqueTogether(
            name='dailygoal',
            unique_together={('student', 'madrasah', 'date')},
        ),
    ]
