# Generated by Django 4.2.30 on 2026-07-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fasaaha', '0003_add_dialogue_session_turn_daily_goal_leaderboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakingattempt',
            name='time_spent_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Time the student spent reading/speaking (seconds)', null=True),
        ),
    ]
