# Generated by Django 4.2.30 on 2026-07-20 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='TajwidAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateField()),
                ('surah_number', models.IntegerField()),
                ('surah_name', models.CharField(max_length=100)),
                ('ayah_range', models.CharField(max_length=100)),
                ('makharij_score', models.IntegerField(blank=True, null=True)),
                ('sifaat_score', models.IntegerField(blank=True, null=True)),
                ('ghunna_score', models.IntegerField(blank=True, null=True)),
                ('madd_score', models.IntegerField(blank=True, null=True)),
                ('waqf_score', models.IntegerField(blank=True, null=True)),
                ('overall_score', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('audio_submission', models.FileField(blank=True, null=True, upload_to='quran/tajwid/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('madrasah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tajwid_assessments', to='users.madrasah')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tajwid_assessments', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_tajwid_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assessment_date'],
            },
        ),
        migrations.CreateModel(
            name='RevisionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surah_number', models.IntegerField()),
                ('surah_name', models.CharField(max_length=100)),
                ('ayah_start', models.IntegerField()),
                ('ayah_end', models.IntegerField()),
                ('revision_date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('madrasah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_schedules', to='users.madrasah')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['revision_date', 'surah_number'],
            },
        ),
        migrations.CreateModel(
            name='PrayerTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fajr', models.TimeField()),
                ('sunrise', models.TimeField()),
                ('dhuhr', models.TimeField()),
                ('asr', models.TimeField()),
                ('maghrib', models.TimeField()),
                ('isha', models.TimeField()),
                ('jumuah_khutbah', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('madrasah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_timetables', to='users.madrasah')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('madrasah', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MemorizationTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surah_number', models.IntegerField()),
                ('surah_name', models.CharField(max_length=100)),
                ('ayah_start', models.IntegerField()),
                ('ayah_end', models.IntegerField()),
                ('memorization_date', models.DateField()),
                ('score', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('madrasah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorizations', to='users.madrasah')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorizations', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_memorizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-memorization_date', 'surah_number'],
                'unique_together': {('student', 'surah_number', 'ayah_start')},
            },
        ),
    ]
