# Generated by Django 4.2.30 on 2026-07-20 18:53

import config.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tajwidassessment',
            name='audio_submission',
            field=models.FileField(blank=True, null=True, upload_to='quran/tajwid/', validators=[config.validators.validate_audio]),
        ),
    ]
