# Generated by Django 4.2.30 on 2026-08-02 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0002_alter_tajwidassessment_audio_submission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrayerTimetable',
        ),
    ]
