# Generated by Django 4.2.30 on 2026-07-20 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date', models.DateField()),
                ('overall_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('madrasah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_evaluations', to='users.madrasah')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_evaluations', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_evaluations_given', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='character_evaluations', to='academic.term')),
            ],
            options={
                'ordering': ['-evaluation_date'],
                'unique_together': {('student', 'evaluation_date', 'teacher')},
            },
        ),
        migrations.CreateModel(
            name='CharacterTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_ar', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('moral', 'Moral'), ('social', 'Social'), ('spiritual', 'Spiritual'), ('academic', 'Academic'), ('personal', 'Personal')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('madrasah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_traits', to='users.madrasah')),
            ],
            options={
                'ordering': ['sort_order'],
                'unique_together': {('madrasah', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CharacterScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(1, 'Poor'), (2, 'Needs Improvement'), (3, 'Satisfactory'), (4, 'Good'), (5, 'Excellent')])),
                ('notes', models.TextField(blank=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='character.characterevaluation')),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='character.charactertrait')),
            ],
            options={
                'unique_together': {('evaluation', 'trait')},
            },
        ),
    ]
