# Generated by Django 4.2.30 on 2026-07-20 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        ('users', '0002_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendations', models.JSONField(default=list)),
                ('recommended_universities', models.JSONField(default=list)),
                ('recommended_courses', models.JSONField(default=list)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_current', models.BooleanField(default=True)),
                ('madrasah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_recommendations', to='users.madrasah')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='AITutorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('madrasah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_tutor_sessions', to='users.madrasah')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_tutor_sessions', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_tutor_sessions', to='curriculum.subject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
