# Generated by Django 4.2.30 on 2026-07-21 09:19

import config.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guidance', '0002_aitutorsession_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tutor_attachments/', validators=[config.validators.validate_tutor_file])),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='guidance.aitutorsession')),
            ],
        ),
    ]
