# Generated by Django 4.2.30 on 2026-07-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['madrasah', 'student'], name='idx_enr_m_student'),
        ),
    ]
