# Generated by Django 4.2.30 on 2026-08-02 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_alter_user_role'),
        ('curriculum', '0002_enrollment_idx_enr_m_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='class_teacher',
            field=models.ForeignKey(blank=True, help_text="The teacher responsible for managing this class's subjects and enrollments.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_teaching', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('madrasah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='users.madrasah')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='curriculum.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='curriculum.subject')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('school_class', 'subject')},
            },
        ),
    ]
