# Generated by Django 4.2.30 on 2026-07-20 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_message'),
        ('curriculum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school_ops', '0002_alter_feepayment_payment_method_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceQRScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('scanner_location', models.CharField(blank=True, max_length=100)),
                ('method', models.CharField(choices=[('qr_code', 'QR Code'), ('rfid', 'RFID'), ('manual', 'Manual')], default='qr_code', max_length=20)),
                ('qr_data', models.TextField(blank=True)),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_scans', to='school_ops.attendance')),
                ('madrasah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_scans', to='users.madrasah')),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_scans', to='curriculum.schoolclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
    ]
