# Generated by Django 4.2.30 on 2026-07-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_ops', '0003_attendanceqrscan'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['madrasah', 'audience'], name='idx_annc_m_audience'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['madrasah', 'date', 'status'], name='idx_att_m_date_status'),
        ),
        migrations.AddIndex(
            model_name='fee',
            index=models.Index(fields=['madrasah', 'status'], name='idx_fee_m_status'),
        ),
        migrations.AddIndex(
            model_name='fee',
            index=models.Index(fields=['madrasah', 'student'], name='idx_fee_m_student'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['fee', 'payment_date'], name='idx_fpay_fee_date'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='idx_notif_rec_read'),
        ),
    ]
