# Generated by Django 4.2.30 on 2026-07-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_email_verified'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['madrasah', 'role', 'is_active'], name='idx_user_m_role_active'),
        ),
    ]
