# Generated by Django 4.2.30 on 2026-08-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_refreshtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guest', 'Guest (Pending Approval)'), ('ustaadh', 'Ustaadh (Teacher)'), ('mudeer', 'Mudeer (Administrator)'), ('idaarah', 'Idaarah (Board)'), ('student', 'Student'), ('parent', 'Parent')], max_length=50),
        ),
    ]
