# Generated by Django 4.2.30 on 2026-08-02 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='madrasah',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='madrasah',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='madrasah',
            name='timezone',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
