# Generated by Django 4.2.30 on 2026-08-02 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_madrasah_latitude_madrasah_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='madrasah',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='madrasah',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='madrasah',
            name='timezone',
        ),
    ]
