# Generated by Django 4.2.30 on 2026-07-24 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_user_date_of_birth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('status_changed', 'Status Changed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published'), ('submitted', 'Submitted'), ('graded', 'Graded'), ('enrolled', 'Enrolled'), ('payment_made', 'Payment Made'), ('login', 'Login'), ('password_change', 'Password Change'), ('other', 'Other')], max_length=50)),
                ('model_name', models.CharField(help_text='app_label.ModelName, e.g. results.SubjectResult', max_length=100)),
                ('object_id', models.CharField(max_length=255)),
                ('object_repr', models.CharField(blank=True, help_text='str() of the object', max_length=300)),
                ('previous_data', models.JSONField(blank=True, default=dict)),
                ('new_data', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('madrasah', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='users.madrasah')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model_name', 'object_id'], name='idx_cal_model_obj'), models.Index(fields=['actor'], name='idx_cal_actor'), models.Index(fields=['madrasah', 'created_at'], name='idx_cal_m_date'), models.Index(fields=['action'], name='idx_cal_action')],
            },
        ),
    ]
