# Generated by Django 4.2.30 on 2026-07-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='hijri_year',
            field=models.IntegerField(blank=True, help_text='e.g. 1446', null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='hijri_end',
            field=models.CharField(blank=True, help_text='e.g. 29 Rabi al-Thani 1446', max_length=50),
        ),
        migrations.AddField(
            model_name='term',
            name='hijri_start',
            field=models.CharField(blank=True, help_text='e.g. 1 Muharram 1446', max_length=50),
        ),
    ]
