# Generated by Django 4.2.30 on 2026-07-20 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_add_email_verified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_type', models.CharField(choices=[('subject_completion', 'Subject Completion'), ('academic_excellence', 'Academic Excellence'), ('quran_memorization', 'Quran Memorization'), ('learning_path', 'Learning Path'), ('achievement', 'Achievement')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('file', models.FileField(blank=True, upload_to='certificates/')),
                ('certificate_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('madrasah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='users.madrasah')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
    ]
