# Generated by Django 4.2.30 on 2026-07-20 18:53

import config.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.FileField(blank=True, upload_to='certificates/', validators=[config.validators.validate_document]),
        ),
    ]
